### ISSUE TITLE
运行报错了，是要安装什么软件吗

### ISSUE THREAD

**Issue by pungyu** [SlimeNull/DouyinCap#1]
DouyinCap 1.0.0
Copyright (C) 2022 SlimeNull

ERROR(S):
  Option 'showbrowser' is unknown.

  --show-browser      (Default: false) Show browser window.

  --post-addr         Specify a http server to post chat message data.

  --help              Display this help screen.

  --version           Display version information.

  room-id (pos. 0)    Required. Live room Id

**Comment by SlimeNull** [comment]
这不是报错

**Comment by SlimeNull** [comment]
是你的操作有问题, 你是直接在 Visual Studio 上运行的调试? 项目上有附加的调试参数, 你应该改成你自己的.
生成程序, 然后使用命令行打开它.

**Comment by SlimeNull** [comment]
程序是要接收参数的... 有时间我去写一个 readme
