### ISSUE TITLE
表情显示为?号 怎么处理？

### ISSUE THREAD

**Issue by iamnewaplayer** [SlimeNull/DouyinCap#2]
表情显示为?号 怎么处理？

**Comment by SlimeNull** [comment]
你可以看看源代码，程序通过获取html节点的文本内容来实现抓取弹幕的，而表情是其他的html节点，它可能是一个图片，这并不能使用纯文本来表示。不过你可以试试解析它，我说的解析html，然后传出一个你可以使用的格式。

Peace & Love
________________________________
From: iamnewaplayer ***@***.***>
Sent: Friday, July 8, 2022 11:39:56 AM
To: SlimeNull/DouyinCap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SlimeNull/DouyinCap] 表情显示为?号 怎么处理？ (Issue #2)


表情显示为?号 怎么处理？

―

**Comment by iamnewaplayer** [comment]
我看起来他是使用的 uft8mb4 
比如送出礼物之类的 收到就是 问号

**Comment by SlimeNull** [comment]
本来就没打算支持表情包捏~
