### ISSUE TITLE
能取到用户uid吗

### ISSUE THREAD

**Issue by zuilaoxian** [SlimeNull/DouyinCap#3]
如题

**Comment by SlimeNull** [comment]
据我所知, 抖音的用户名是唯一的, 在 HTML 中也没有直接写明 UID, 所以, 目前不打算直接支持获取用户 UID, 但是, 可以提供一个思路, 同样借助这个无头浏览器, 你可以访问抖音的搜索 API, 然后拿到第一个搜索结果的用户 UID, 就 ok 了.
________________________________
发件人: zuilaoxian ***@***.***>
发送时间: 2022年7月31日 14:10
收件人: SlimeNull/DouyinCap ***@***.***>
抄送: Subscribed ***@***.***>
主题: [SlimeNull/DouyinCap] 能取到用户uid吗 (Issue #3)


如题

―
