### ISSUE TITLE
抖音弹幕数据信息

### ISSUE THREAD

**Issue by lichao252244354** [SlimeNull/DouyinCap#6]
请问执行完DouyinCap 114514抓取的弹幕数据在哪里生成，一直没有找到

**Comment by SlimeNull** [comment]
我的建议是, 看看我在 bilibili 的演示视频. 这个爬虫仅爬取数据, 不存储数据. 而与其他程序交互的手段是, http 请求.

例如你正在编写一个程序, 他需要抖音爬虫数据, 那么你可以让他监听本地端口, 并且接受 http 请求, 然后在爬虫启动时传入上报地址, 爬虫在接收到弹幕数据的时候, 就会通过 http 请求, 发送给你的程序.

如果你不是一个程序员, 我不是非常推荐你使用这个项目, 因为这个项目并不是一个完整的应用程序, 他更适用于作为项目中的其中一个组件.

参考之前比较火的 "在线游戏", 它就是需要抓取弹幕信息. 而你的游戏则应该是一个 Unity 程序, 你需要的是让这个 Unity 程序监听并接受 http 请求, 拿到数据, 然后实现交互.
