### ISSUE TITLE
请问如何查看DouyinCap --post-addr http://127.0.0.1:1145 114514返回的post数据信息

### ISSUE THREAD

**Issue by lichao252244354** [SlimeNull/DouyinCap#7]
在终端启动DouyinCap --post-addr http://127.0.0.1:1145 114514后如何查看返回的post数据信息呢？执行完后就没有了

**Comment by SlimeNull** [comment]
因为程序只负责上报,,, 管他响应什么呢, 我上报了就完事儿了hhh
如果你需要拓展一些东西, 可以自己fork下来, 然后改改, 再 pull request
