### ISSUE TITLE
执行DouyinCap 114514后没有弹幕信息显示

### ISSUE THREAD

**Issue by lichao252244354** [SlimeNull/DouyinCap#8]
在终端执行DouyinCap.exe 114514 后没有相关弹幕信息在终端显示,debug发现 var nameNode = await item.QuerySelectorAsync(".tfObciRM");
                        var valueNode = await item.QuerySelectorAsync(".Wz8LGswb"); 获取的nameNode 和valueNode 是null，这两个参数tfObciRM和Wz8LGswb是什么含义呢

**Comment by SlimeNull** [comment]
是抖音的憨批 CSS 类, 简单来讲就是弹幕节点类

**Comment by SlimeNull** [comment]
有一说一, 如果抖音前端变了, 那这个项目也得跟着变, 谁让抖音用了憨批随机类名, 害... (懒得改噢... 要不你来改改?

**Comment by SlimeNull** [comment]
不过我最近开了新项目, LiveMessagePost, 那个是一个 chrome 插件, 同样是将弹幕信息通过 http 推送到指定地址的, 支持抖音, 快手, bilibili, 虎牙这四个平台, 当然也是免费使用的芜湖~~~

**Comment by lichao252244354** [comment]
这个仓库在哪里呢？可以分享给我使用下吗？谢谢了

**Comment by SlimeNull** [comment]
害... 但凡你有去我主页里看也不至于问出这种问题, 里面写得清清楚楚了... 如果好用, 记得点小星星, 点小星星! 
https://github.com/SlimeNull/LiveMessagePosting

**Comment by lichao252244354** [comment]
OK,谢谢，我跑一下看能不能正常运行

**Comment by lichao252244354** [comment]
能支持淘宝弹幕吗？谢谢了

**Comment by SlimeNull** [comment]
你自己会写吗, 代码会看吗

**Comment by lichao252244354** [comment]
代码会看，但是我看只支持 支持抖音, 快手, bilibili, 虎牙

**Comment by SlimeNull** [comment]
那你自己可以添加想要的功能啊

**Comment by lichao252244354** [comment]
淘宝的写不来，你帮我看下怎么添加，可以吗？

**Comment by SlimeNull** [comment]
你是要商用吗

**Comment by lichao252244354** [comment]
不商用

**Comment by lichao252244354** [comment]
我有个任务需要抓取淘宝的弹幕

**Comment by lichao252244354** [comment]
我搜索了下，只有你这个比较全一些，但是好像不支持淘宝

**Comment by SlimeNull** [comment]
你写一下你联系方式, QQ 什么的, 咱 QQ 上聊

**Comment by lichao252244354** [comment]
微信吧，现在谁还用qq
138****3754

---
作者已将微信号隐藏

**Comment by SlimeNull** [comment]
你这话就离谱了, 现在什么编程交流群, 我都没在微信上见到过

**Comment by lichao252244354** [comment]
哈哈，我QQ很多年没有用过了

**Comment by lichao252244354** [comment]
QQ号都记不得了

**Comment by SlimeNull** [comment]
加你微信了
